apiVersion: v1
kind: Service
metadata:
  name: insureme-service
  namespace: insureme-ns
spec:
  type: ClusterIP
  selector:
    app: insureme
  ports:
    - port: 8081
      targetPort: 8089
      protocol: TCP